#!/bin/bash
# Clean up duplicate sources and install Intel drivers

set -e

echo "Fixing sources.list and installing Intel drivers..."
echo ""

# Backup current sources
cp /etc/apt/sources.list /etc/apt/sources.list.backup

# Create clean sources.list
cat > /etc/apt/sources.list <<'EOF'
# Generated by distrobuilder
deb http://deb.debian.org/debian trixie main contrib non-free non-free-firmware
deb http://deb.debian.org/debian trixie-updates main contrib non-free non-free-firmware
deb http://deb.debian.org/debian-security/ trixie-security main contrib non-free non-free-firmware
EOF

echo "✓ Fixed sources.list"
echo ""

# Update package lists
echo "Updating package lists..."
apt-get update

echo ""
echo "Installing Intel drivers and dependencies..."

# Install Intel GPU drivers
apt-get install -y \
    intel-media-va-driver-non-free \
    intel-gpu-tools \
    vainfo \
    libva2 \
    libva-drm2 \
    libvpl2 \
    libvpl-dev \
    i965-va-driver \
    mesa-va-drivers \
    firmware-misc-nonfree

echo ""
echo "✓ Intel drivers installed!"
echo ""

# Test VAAPI
echo "Testing VAAPI..."
if LIBVA_DRIVER_NAME=iHD vainfo 2>&1 | grep -q "iHD"; then
    echo "✓ VAAPI is working!"
else
    echo "⚠ VAAPI test had issues"
fi

echo ""
echo "Installed packages:"
dpkg -l | grep -E "intel-media|libvpl|vainfo" | grep ^ii

